### ISSUE TITLE
Upgrade to elasticsuite 2.9 version

### ISSUE THREAD

**Issue by Amadeco** [Smile-SA/magento2-module-elasticsuite-rating#13]
Afternoon,

I would like to know if you can raise your number version, and correct, your composer.json with a more restrictless requirement :

https://github.com/Smile-SA/magento2-module-elasticsuite-rating/blob/29780ee72563fb9f77785a0adf29e65d3acbbda7/composer.json#L35

with equal or higher version ^2.7
I do not know if you had the time to make some test with your last version.

Actually, we can not upgrade elasticsuite to the last version, this plugin block the way through.

I know you just get through your release,

Ilan

**Comment by KZNcode** [comment]
Same issue. 

Shouldn't this extension just be merged into the main release by now. Narrowing down by rating is pretty much standard best practices.

**Comment by Amadeco** [comment]
@romainruaud Do you have spare time about this issue ? :-)
Thank you

**Comment by KZNcode** [comment]
Here's to start a new install  (this is likely the **best method**; but worked without any of the modification above on a new install):

`composer require smile/module-elasticsuite-rating --ignore-platform-reqs`


*********
Or if you got a previous install and above don't work, try this:

Basically, as you noted, you need to change all the instances of ~ with ^ in both composer.json and composer.lock

Here's what I did with a previous install (forgot exactly)  :

`
find . -type f -name "composer.*" -exec sed -i 's|"smile/elasticsuite" : "~2.7.0"|"smile/elasticsuite": "^2.8.0"|g' {} \;

find . -type f -name "composer.*" -exec sed -i 's|"smile/elasticsuite" : "~2.8.0"|"smile/elasticsuite": "^2.8.0"|g' {} \;

composer update

# or try:
composer require smile/module-elasticsuite-rating --ignore-platform-reqs

`

I haven't fully bug tested this yet, but it did allow the upgrade.

**Comment by rbayet** [comment]
The Elasticsuite requirement has been changed in release [2.3.2](https://github.com/Smile-SA/magento2-module-elasticsuite-rating/releases/tag/2.3.2) from ~2.8.0 to ^2.8.0, which allows installing the module on Elasticsuite
- 2.8.x versions (M2 2.3.x < 2.3.5)
- 2.9.x versions (M2 2.3.x >= 2.3.5)
- 2.10.x versions (M2 2.4.x)

Regards,
