### ISSUE TITLE
Composer install fails

### ISSUE THREAD

**Issue by OvalMedia** [Smile-SA/magento2-module-elasticsuite-rating#14]
I have smile/elasticsuite version 2.10.3 installed.

`composer require smile/module-elasticsuite-rating`

...fails with...

```
Problem 1
    - smile/module-elasticsuite-rating 2.3.1 requires smile/elasticsuite ~2.8.0 -> satisfiable by smile/elasticsuite[2.8.0, 2.8.1, 2.8.10, 2.8.11, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.8.7, 2.8.8, 2.8.9, 2.8.x-dev] but these conflict with your requirements or minimum-stability.
    - smile/module-elasticsuite-rating 2.3.0 requires smile/elasticsuite ~2.7.0 -> satisfiable by smile/elasticsuite[2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.7.5, 2.7.6, 2.7.7, 2.7.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for smile/module-elasticsuite-rating ^2.3 -> satisfiable by smile/module-elasticsuite-rating[2.3.0, 2.3.1].

```

Adding `--ignore-platform-reqs` doesn't make a difference.

**Comment by KZNcode** [comment]
Bump... Already brought this up here and in elasticsuite issues last year... But thus far not attention brought to this.

**Comment by OvalMedia** [comment]
Is this project abandoned? This module is still not installable.

**Comment by Amadeco** [comment]
Do not know if we need a complete revision of the module for the new ElasticSuite and Magento 2.4 version compability, but any support from you would be greatly appreciated, I imagine you must have much work to do.
If it only a problem with composer requirements, it must be very easy to fix.

@romainruaud 
@delyriand 
@rbayet

**Comment by OvalMedia** [comment]
I installed it manually on a 2.4.2-p1and it failed immediately.

Installation, setup and compile went fine but when I open the store (frontend) it fails with this error:

`The XML in file "/app/code/Smile/ElasticsuiteRating/etc/elasticsuite_indices.xml" is invalid: Element 'datasources': This element is not expected. Expected is ( mapping ). Line: 23 Verify the XML and try again.`

**Comment by Amadeco** [comment]
Hi

You can test my pull request : #15,
Test on the last version of Magento 2.4.3

Ilan

**Comment by OvalMedia** [comment]
I can confirm that the error is gone. Also the sorting options now appear in the product list. But it is not clear what the system is sorting by now. I checked the new eav field `ratings_summary` in the products. They are all empty. I installed this in a store which already has a lot of reviews and ratings. Am I right to assume that this value needs to be filled over time?

**Comment by OvalMedia** [comment]
For testing I filled some ratings manually and sorted by `?product_list_dir=desc&product_list_order=ratings_summary`.
I would expect the products with values in ratings_summary to be on top of the list but that is not the case.

The select looks like this:

`SELECT `e`.*, `price_index`.`price`, `price_index`.`tax_class_id`, `price_index`.`final_price`, IF(price_index.tier_price IS NOT NULL, LEAST(price_index.min_price, price_index.tier_price), price_index.min_price) AS `minimal_price`, `price_index`.`min_price`, `price_index`.`max_price`, `price_index`.`tier_price`, IFNULL(review_summary.reviews_count, 0) AS `reviews_count`, IFNULL(review_summary.rating_summary, 0) AS `rating_summary`, `stock_status_index`.`stock_status` AS `is_salable` FROM `catalog_product_entity` AS `e` INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.customer_group_id = 0 AND price_index.website_id = '1' LEFT JOIN `review_entity_summary` AS `review_summary` ON e.entity_id = review_summary.entity_pk_value AND review_summary.store_id = 1 AND review_summary.entity_type = (SELECT `review_entity`.`entity_id` FROM `review_entity` WHERE (entity_code = 'product')) INNER JOIN `cataloginventory_stock_status` AS `stock_status_index` ON e.entity_id = stock_status_index.product_id AND stock_status_index.website_id = 0 AND stock_status_index.stock_id = 1 WHERE (stock_status_index.stock_status = 1) AND (e.entity_id IN (1523, 1610, 1618, 1620, 1621, 1623, 1706, 1734, 1735, 1736, 1737, 1766, 1768, 1780, 1816, 1819, 1844, 1847, 1904, 1905)) ORDER BY FIELD(e.entity_id,1523,1610,1618,1620,1621,1623,1706,1734,1735,1736,1737,1766,1768,1780,1816,1819,1844,1847,1904,1905)`

**Comment by Amadeco** [comment]
> I can confirm that the error is gone. Also the sorting options now appear in the product list. But it is not clear what the system is sorting by now. I checked the new eav field `ratings_summary` in the products. They are all empty. I installed this in a store which already has a lot of reviews and ratings. Am I right to assume that this value needs to be filled over time?

You can wait for the cron task doing it job if you are in production or you can reindex you elasticsearch indexes by performing a command in your ssh console (bin/magento indexer:reindex) to populate the new attribute rating_summary.

**Comment by OvalMedia** [comment]
I did that (also cron is active) but that did not populate the "Product Rating" field in the products.
Where should this value come from?

**Comment by OvalMedia** [comment]
For some weird reason the sorting function works now. The value in the product's fields is always 0 though. I assume it's real value is somehow taken from the actual review data?

**Comment by rbayet** [comment]
Hello @OvalMedia,

Yes by the look at the SQL request you posted the indexed data comes straights from the `review_entity_summary` table.
I'm not sure about the role of the `ratings_summary` field in the products.

Anyway, I'm going to look at @mageho PR.

And yes, the module was kinda living its own (sad and monotone) life a bit apart from Elasticsuite's because @romainruaud and I focus our attention on Elasticsuite and can easily miss issues on related modules (which are numerous !)

Regards

**Comment by OvalMedia** [comment]
Thx for your feedback and thx for your efforts. Much appreciated.

**Comment by rbayet** [comment]
Hello @OvalMedia,

You should be able to install the 2.3.2 release on your M2 2.4.x/Elasticsuite 2.10.x environment.

Regards,
