### ISSUE TITLE
Bug: Conflict with getRatingSummary method

### ISSUE THREAD

**Issue by Leone** [Smile-SA/magento2-module-elasticsuite-rating#2]
Hi,

This extension works great, but I found one bug.
If I edit and save the product in the admin panel, magento saves decimal value for attribute rating_summary.
Unfortunately, it breaks review/rating section on PDP because magento is not able to get the RatingSummary object.

$product->getRatingSummary(); returns decimal value instead of review/rating summary object.

magento CE, 2.1.7

**Comment by romainruaud** [comment]
@Leone for me this issue is not related to the module.

The module is never called anywhere in the PDP. This is full standard Magento rendering.

Did you try to reproduce this bug without our module on a clean magento install ?

Regards.

**Comment by chris-brabender** [comment]
Same issue identified on magento 2.2.2 EE, occurs on Configurable products.

**Comment by yaronish** [comment]
Hi, @romainruaud 
See \Magento\Review\Block\Product\ReviewRenderer::getReviewsSummaryHtml().
There are few calls to $product->getRatingSummary() which expect DataObject as return result. 
Having attribute 'rating_summary' loaded with product data it returns decimal instead.

**Comment by romainruaud** [comment]
@yaronish yes I agree, there is a collision between the both items.

Will work on it and try to provide a fix soon.

Best regards.

**Comment by romainruaud** [comment]
I published a new version where the collisioning attribute is now renamed.

Let me know if the issue is still happening.

regards
