### ISSUE TITLE
Add require php 7.1 for composer

### ISSUE THREAD

**Issue by minhluan259** [Smile-SA/magento2-module-elasticsuite-rating#3]
Please add require php 7.1 for composer.jon
"php" : "~5.5.0|~5.6.0|~7.0.0|~7.1.0"

**Comment by minhluan259** [comment]
@romainruaud please merge the request #4

**Comment by romainruaud** [comment]
I removed the dependency to any PHP version.

Magento will handle it by itself.

Please update to latest release.

Regards
