### ISSUE TITLE
Help Needed With M2.2.2

### ISSUE THREAD

**Issue by pete79** [Smile-SA/magento2-module-elasticsuite-rating#5]
We've installed this module on M2 v2.2.2. However we seem to be having an issue where clicking any of the stars redirects with parameter always review_summary=0. Reproduced with blank and luma themes. Also the width is always 0 % in the following 
`<span data-bind="style: {width : label + '%'}" style="width: 0%;"></span>`

**Comment by romainruaud** [comment]
Actually, we do not reproduce this (very old) issue.

I Close this for being way too much outdated. Feel free to open a new issue if you're still encountering it.
